//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompApp.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractClient
    {
        public int IdContractClient { get; set; }
        public int IdContract { get; set; }
        public int IdClient { get; set; }
        public Nullable<double> CoefAgeDriver { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual InsuranceContract InsuranceContract { get; set; }
    }
}
