//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompApp.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceCompanyDBEntities : DbContext
    {
        private static InsuranceCompanyDBEntities _context;
        public InsuranceCompanyDBEntities()
            : base("name=InsuranceCompanyDBEntities")
        {
        }
        public static InsuranceCompanyDBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new InsuranceCompanyDBEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassKBM> ClassKBM { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ContractClient> ContractClient { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<InsuranceContract> InsuranceContract { get; set; }
        public virtual DbSet<InsuranceType> InsuranceType { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<StatusContract> StatusContract { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
    }
}
